
# A minimal left prompt
format = """
$directory\
$character
"""

continuation_prompt = "[â–¶](242)"

# move the rest of the prompt to the right
right_format = """$all"""

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1
style = "066"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[cmd_duration]
disabled = true

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
symbol = "ï˜ "

[gcloud]
disabled = true

[git_status]
format ="([$all_status$ahead_behind]($style) )"
behind = "â¬‡ï¸"
ahead = "â¬†ï¸"
diverged = "â†•ï¸"
modified = "â—"
untracked = "â“"
stashed = "ğŸ“‚"
# up_to_date = "âœ”ï¸"

[package]
format = "/ [$symbol$version]($style) "
symbol = "ğŸ“¦ "

[java]
format = "/ [${symbol}(${version} )]($style)"
version_format ="${raw}"
style = "bright-blue"
symbol = "î‰– "

[python]
format = '/ [${symbol}${pyenv_prefix}(${version} )]($style)[(\($virtualenv\) )](028)'

version_format ="${raw}"
symbol = "î˜† "

[rust]
format = "/ [${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = "î¨ "

[nodejs]
format = "/ [${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = "î˜Œ "

[lua]
format = "/ [${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = "î˜  "

[c]
format = "/ [${symbol}(${version} )]($style)"
version_format ="${raw}"
symbol = "î˜ "
