gui:
  nerdFontsVersion: "3"
  shortTimeFormat: 13:04
  showListFooter: false
  showBottomLine: false
  theme:
    # Border color of focused window
    activeBorderColor:
      - green
      - bold
    # Border color of non-focused windows
    inactiveBorderColor:
      - "#555"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
customCommands:
  - key: '<c-l>'
    context: 'reflogCommits'
