[tools]
usage = "latest"
fzf = "latest"
yq = "latest"
jq = "latest"
rg = "latest"
fd = "latest"
lsd = "latest"
zoxide = "latest"
btop = "latest"
gh = "latest"
lazygit = "latest"
delta = "latest"
jj = "latest"
gitleaks = "latest"
trivy = "latest"
kubectl = "latest"
helm = "latest"
node = "latest"

[settings]
experimental = true

trusted_config_paths = [
  "$HOME/workspace",
  "$HOME/.dotfiles"
]

[settings.python]
uv_venv_auto = true

[alias.java.versions]
8 = "zulu-8.84.0.15"
