[tools]
usage = "latest"
fzf = "latest"
yq = "latest"
jq = "latest"
rg = "latest"
fd = "latest"
lsd = "latest"
zoxide = "latest"
btop = "latest"
gh = "latest"
lazygit = "latest"
delta = "latest"
gitleaks = "latest"
trivy = "latest"
kubectl = "latest"
helm = "latest"
# --- languages ---
rust = { version = "1.89.0", profile = "default" }
java = "25"
python = "latest"
go = "latest"
deno = "latest"
nodejs = "latest"
opam = "latest"

[settings]
experimental = true

trusted_config_paths = [
  "~/workspace",
  "~/.dotfiles"
]
idiomatic_version_file_enable_tools = ["python"]

[settings.python]
uv_venv_auto = true

[alias.java.versions]
8 = "corretto-8"
17 = "corretto-17"
25 = "corretto-25"
lts = "corretto-25"
latest = "corretto-25"
